// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpe2CHAP_WwMxVI_Gb2WStT0iyUWLpctA',
    appId: '1:70416475933:web:220a4e826e7667f69963f4',
    messagingSenderId: '70416475933',
    projectId: 'fir-flutter-codelab-9acab',
    authDomain: 'fir-flutter-codelab-9acab.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-9acab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsJOjsWoUhRIIVK9gKWua2liSQNIsk9o',
    appId: '1:70416475933:android:3eba13d058f0ee829963f4',
    messagingSenderId: '70416475933',
    projectId: 'fir-flutter-codelab-9acab',
    storageBucket: 'fir-flutter-codelab-9acab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOQkXj_MeHGdnz4gY3yAoA6Ky0d1PikE',
    appId: '1:70416475933:ios:d45d5a0f1349598b9963f4',
    messagingSenderId: '70416475933',
    projectId: 'fir-flutter-codelab-9acab',
    storageBucket: 'fir-flutter-codelab-9acab.appspot.com',
    iosClientId: '70416475933-js7gjgstvl6fc7l10r44vafo13a2k9nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzOQkXj_MeHGdnz4gY3yAoA6Ky0d1PikE',
    appId: '1:70416475933:ios:d45d5a0f1349598b9963f4',
    messagingSenderId: '70416475933',
    projectId: 'fir-flutter-codelab-9acab',
    storageBucket: 'fir-flutter-codelab-9acab.appspot.com',
    iosClientId: '70416475933-js7gjgstvl6fc7l10r44vafo13a2k9nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
